### ISSUE TITLE
Better Define Use of Macros in Elixirscript

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#159]
Currently, you can pass in a `Macro.Env` to any of the `ElixirScript.compile`* functions and it will use that to expand macros in elixirscript code. This works when calling the compiler from code, but not when using it from the cli.

The plan is to borrow from clojurescript's way of using macros
https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure#macros

This Issue is to do the following:
* Officially adopt `.exjs` as extension for elixirscript code
* Use `.ex` and `.exs` strictly for loading modules that contain macros
* Load `.ex` and `.exs` files found in path using `Code.load_file/1`
* Traverse elixirscript code to find import and require expressions
  * If module imported or required is a loaded module it is assumed to be used for macros
  * Otherwise, it will continue to work as it does now
* When updating the `ElixirScript.Macro.Env` for the current scope, create a code snippet with the imports and requires needed and use `Code.eval_string\3` passing in the current `Macro.Env` so that scope can use macros as needed. Using new `Macro.Env` when calling `Macro.expand\2` to expand macros. The current `Macro.Env` will need to be added as a field to `ElixirScript.Macro.Env`

What also needs to be tested is if this will for work for `use` and `__using__`

A small code example of how to get the env using a loaded file
```elixir
    # Load file and get modules from file.
    {module, _} = Code.load_file("my_elixir_module_containing_macros.ex") |> List.first

    # Create string to eval using import and require statements found
    eval = """
    require #{module |> Atom.to_string |> String.replace("Elixir.", "")}
    __ENV__
    """

    # Eval above string passing in the current Macro.Env to get back a new one
    {env, _} = Code.eval_string(eval, [], __ENV__)
    # Use this when calling Macro.expand
    env

```

### Subtasks
- [x] Update ElixirScript.compile_path to call `Code.load_file` on any file with a `.ex` or `.exs` extension
- [x] Update ElixirScript.Macro.Env to include an `env` field containing a `Macro.Env`
- [x] When creating a new ElixirScript.Macro.Env for a module, pass in the env from the compiler
- [x] When an import or require is encountered check loaded module list to see if it should be used for macro expansion. If not in loaded list, do current functionality
- [x] Add the ability to create a `Macro.Env` from an existing `Macro.Env` and import/require statements using `Code.eval_string`

**Comment by bryanjos** [comment]
Another possible idea is to:
1. Load files using Code.load_file
2. Use Macro.prewalk to find require and import statements
3. Use information to create a module with a get_env function of some kind
4. Load that file using Code.load_file
5. Call get_env function to env and use it on code.

I don't know if it'll work, but it's worth a shot
